### ISSUE TITLE
An unexpected exception occurred

### ISSUE THREAD

**Issue by andrewharvey** [JOSM/Mapillary#159] opened 2020-12-26 21:43 UTC
After some random time when using the plugin JOSM reports "An unexpected exception occurred."
```
{{{
Revision:17329
Is-Local-Build:false
Build-Date:1969-12-29 18:00:08
Debian-Release:0.0.svn17329+dfsg-1
Build-Name:Debian

Identification: JOSM/1.5 (17329 Debian en_AU) Linux Debian GNU/Linux bullseye/sid
Memory Usage: 1072 MB / 3974 MB (506 MB allocated, but free)
Java version: 11.0.9.1+1-post-Debian-1, Debian, OpenJDK 64-Bit Server VM
Look and Feel: javax.swing.plaf.metal.MetalLookAndFeel
Screen: :0.0 1920x1080 (scaling 1.0x1.0)
Maximum Screen Size: 1920x1080
Best cursor sizes: 16x16 -> 16x16, 32x32 -> 32x32
Java package: openjdk-11-jre:amd64-11.0.9.1+1-1
Java ATK Wrapper package: libatk-wrapper-java:all-0.38.0-1
Environment variable LANG: en_AU.UTF-8
libcommons-compress-java: libcommons-compress-java:all-1.20-1
libcommons-logging-java: libcommons-logging-java:all-1.2-2
fonts-noto: fonts-noto:all-20201109-1
liboauth-signpost-java: liboauth-signpost-java:all-1.2.1.2-3
VM arguments: [--add-modules=java.scripting,java.sql, -Djosm.restart=true, -Djava.net.useSystemProxies=true]
Dataset consistency test: No problems found

Plugins:
...
+ Mapillary (1.5.30)
...

=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: mapillary-MapillarySquareDownloadRunnable-5 (971)
java.lang.IllegalArgumentException
	at org.openstreetmap.josm.plugins.mapillary.data.image.MapillaryAbstractImage.setSequence(MapillaryAbstractImage.java:327)
	at org.openstreetmap.josm.plugins.mapillary.utils.api.JsonImageDetailsDecoder.decodeImageInfo(JsonImageDetailsDecoder.java:95)
	at org.openstreetmap.josm.plugins.mapillary.utils.api.JsonImageDetailsDecoder.lambda$decodeImageInfos$0(JsonImageDetailsDecoder.java:52)
	at org.openstreetmap.josm.plugins.mapillary.utils.api.JsonDecoder.decodeFeatureCollection(JsonDecoder.java:44)
	at org.openstreetmap.josm.plugins.mapillary.utils.api.JsonImageDetailsDecoder.decodeImageInfos(JsonImageDetailsDecoder.java:52)
	at org.openstreetmap.josm.plugins.mapillary.io.download.ImageDetailsDownloadRunnable.run(ImageDetailsDownloadRunnable.java:56)
	at org.openstreetmap.josm.plugins.mapillary.io.download.BoundsDownloadRunnable.realRun(BoundsDownloadRunnable.java:116)
	at org.openstreetmap.josm.plugins.mapillary.io.download.BoundsDownloadRunnable.realRun(BoundsDownloadRunnable.java:80)
	at org.openstreetmap.josm.plugins.mapillary.io.download.BoundsDownloadRunnable.lambda$run$0(BoundsDownloadRunnable.java:70)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
}}}
```

**Comment by GhostFoxSledgehammer** [comment] 2020-12-28 05:58
This looks similar to JOSM [#20294](https://josm.openstreetmap.de/ticket/20294) which was fixed in 454aef2 and released in v1.5.31.
Try updating the plugin to see if the problem persists.

**Comment by tsmock** [comment] 2020-12-28 14:22
This does look like JOSM-20294. I was going to write a non-regression test for this sometime this week, as soon as I'm able to actually reproduce. And have the time.

Also, in the future, can you avoid clipping information from the bug report?

Thanks. I'm going to close this since I *think* it was fixed in v1.5.31.

(Also, feel free to report bugs on the JOSM bug tracker).

**Closed by tsmock** 2020-12-28 14:22 UTC

**Comment by andrewharvey** [comment] 2020-12-29 05:31
I still ran into this with 1.5.32.

I tried to clip out information which was more private and about my specific setup, but I've left that in now.

I thought it was an issue with the plugin because it only happens with the plugin and the stack trace points to the plugin, but I can report on JOSM side if you think it's more their issue (I just find their bug reporting software a pain to use).

```
{{{
Revision:17329
Is-Local-Build:false
Build-Date:1969-12-29 18:00:08
Debian-Release:0.0.svn17329+dfsg-1
Build-Name:Debian

Identification: JOSM/1.5 (17329 Debian en_AU) Linux Debian GNU/Linux bullseye/sid
Memory Usage: 1719 MB / 3974 MB (962 MB allocated, but free)
Java version: 11.0.9.1+1-post-Debian-1, Debian, OpenJDK 64-Bit Server VM
Look and Feel: javax.swing.plaf.metal.MetalLookAndFeel
Screen: :0.0 1920x1080 (scaling 1.0x1.0)
Maximum Screen Size: 1920x1080
Best cursor sizes: 16x16 -> 16x16, 32x32 -> 32x32
Java package: openjdk-11-jre:amd64-11.0.9.1+1-1
Java ATK Wrapper package: libatk-wrapper-java:all-0.38.0-1
Environment variable LANG: en_AU.UTF-8
libcommons-compress-java: libcommons-compress-java:all-1.20-1
libcommons-logging-java: libcommons-logging-java:all-1.2-2
fonts-noto: fonts-noto:all-20201109-1
liboauth-signpost-java: liboauth-signpost-java:all-1.2.1.2-3
VM arguments: [--add-modules=java.scripting,java.sql, -Djosm.restart=true, -Djava.net.useSystemProxies=true]
Dataset consistency test: No problems found

Plugins:
+ FastDraw (35640)
+ ImproveWay (29)
+ Mapillary (1.5.32)
+ apache-commons (35524)
+ apache-http (35589)
+ buildings_tools (35669)
+ comfort0 (35640)
+ conflation (0.6.6)
+ editgpx (35562)
+ ejml (35458)
+ flatlaf (35652)
+ geotools (35458)
+ javafx-unixoid (35655)
+ jaxb (35543)
+ jna (35662)
+ jts (35458)
+ measurement (35640)
+ native_password_manager (35665)
+ opendata (35640)
+ pbf (35640)
+ photo_geotagging (35640)
+ photoadjust (35640)
+ reverter (35640)
+ rex (53)
+ tageditor (35640)
+ terracer (35640)
+ turnlanes (35640)
+ turnlanes-tagging (288)
+ turnrestrictions (35640)
+ undelete (35640)
+ utilsplugin2 (35674)
+ wikipedia (1.1.4)

Tagging presets:
+ /usr/share/josm/data/defaultpresets.xml
+ https://raw.githubusercontent.com/yopaseopor/traffic_signs_preset_JOSM/master/AU.zip
+ https://raw.githubusercontent.com/osmlab/name-suggestion-index/master/dist/name-suggestions.presets.xml

Map paint styles:
- /usr/share/josm/styles/standard/potlatch2.mapcss
- https://raw.githubusercontent.com/yopaseopor/indoormap/master/indoormap-style.mapcss
- https://josm.openstreetmap.de/josmfile?page=Styles/Admin_Boundaries&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/SlovakiaBicycleRoutes&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Cycleways&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Enhanced_Lane_and_Road_Attributes&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/iD&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Lane_and_Road_Attributes&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/LessObtrusiveNodes&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Maxspeed&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/MTB&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Mountains&zip=1
- https://raw.githubusercontent.com/OpenSidewalks/OpenSidewalks-Schema/master/open_sidewalks.mapcss
- https://josm.openstreetmap.de/josmfile?page=Styles/Osmc&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/ParkingLanes&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/PublicTransport&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/sac_scale&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Sidewalks&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Surface&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Fixme&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Noname&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/MapWithAI&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Lit&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/LitObjects&zip=1

Last errors/warnings:
- 00289.672 E: Unknown detection "object--traffic-sign"
- 00300.462 W: java.net.SocketTimeoutException: Read timed out. Cause: java.net.SocketTimeoutException: Read timed out
- 00300.894 E: Unknown detection "regulatory--texts-four-lines--g1"
- 00300.894 E: Unknown detection "regulatory--texts-four-lines--g1"
- 00302.840 E: Unknown detection "regulatory--texts-four-lines--g1"
- 00314.498 W: java.net.SocketTimeoutException: Read timed out. Cause: java.net.SocketTimeoutException: Read timed out
- 00322.242 W: Server timeout, trying https://a.mapillary.com/v3/images?client_id=UTZhSnNFdGpxSEFFREUwb01GYzlXZzpjNGViMzQxMTIzMjY0MjZm&_next_page_token=eyJhZnRlciI6WzE1ODU3NjE5ODA0MTQsImpqS3JrckNvbkJvcFpjUXM5Uk5scGciXX0%3D&bbox=151.1381435%2C-33.8336347%2C151.1953925%2C-33.764521 again (attempt 1 of 2)
- 00322.243 W: java.io.IOException: javax.json.JsonException: I/O error while auto-detecting the encoding of stream. Cause: javax.json.JsonException: I/O error while auto-detecting the encoding of stream. Cause: java.io.IOException: stream is closed
- 00330.334 E: java.io.IOException: stream is closed
- 00361.071 E: Unknown detection "regulatory--texts-four-lines--g1"


=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: AWT-EventQueue-0 (19) of main
java.lang.NullPointerException
	at org.openstreetmap.josm.plugins.mapillary.gui.MapillaryMainDialog.updateDisplayImage(MapillaryMainDialog.java:527)
	at org.openstreetmap.josm.plugins.mapillary.gui.MapillaryMainDialog.lambda$updateDetections$3(MapillaryMainDialog.java:517)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
}}}
```

**Comment by tsmock** [comment] 2020-12-29 14:24
That is a different issue. Still a Mapillary plugin problem.
