### ISSUE TITLE
Traffic sign indicator not shown

### ISSUE THREAD

**Issue by grinapo** [JOSM/Mapillary#46] opened 2017-04-04 17:31 UTC
Feature set mentions the plugin handles traffic signs. There is no visible sign of that. I looked up an image on the web GUI, checked it in JOSM. Icon same, and when I filter for signs there are zero images.

**Comment by floscher** [comment] 2017-04-04 19:56
@grinapo I'm currently working on the traffic sign support, it will ship with the next release.

The feature mentioned on https://wiki.openstreetmap.org/wiki/JOSM/Plugins/Mapillary#Features just means that currently the green dots on the map have a small red-white triangle on top, if the image contains traffic signs, nothing more.

I now removed `Look for signs in the downloaded images` from the wiki page, because it is both unspecific and misleading.

**Comment by grinapo** [comment] 2017-04-06 06:55
@floscher Thanks, but I don't even see the triangle, and I am using dev-latest josm with updated plugins. (Triangle would help a lot as well as a starter...)

**Comment by floscher** [comment] 2017-04-06 13:24
Can you confirm, that the triangles are not loading when loading the following OSM data into JOSM?:
http://127.0.0.1:8111/load_and_zoom?left=12.995977931749367&right=12.999977931749369&top=55.61834659910291&bottom=55.6143465991029 (link only works when JOSM is running with active remote control)

Because I can't reproduce your issue using JOSM 11826 and Mapillary plugin v1.4.2.
After about six seconds for me two triangles appear on top of the green dots, like this:
![screenshot](https://cloud.githubusercontent.com/assets/3904348/24755968/62dbf136-1adc-11e7-88b4-4f44213b0847.png)

It could be, that signs, which were recently detected are not shown, because Mapillary serves objects, which were detected after a certain date only over the new APIv3 and the APIv2 only serves "old detections" from before that date.

The current stable version still uses APIv2, but the next release will use the APIv3 for the majority of requests.

**Comment by grinapo** [comment] 2017-04-06 21:26
Your triangles are visible. Mine aren't. 
`  Bounding box: 18.798893, 47.6611758, 18.7990414, 47.661253`
But these are "recent" (within half a year), so maybe APIv3 going to fix it.

**Comment by floscher** [comment] 2017-04-07 15:34
Thank you for providing your coordinates. This seems to be a bug in the Mapillary API (only v2, the new v3 is fine).

When I request the bounding box `18.7965613604,47.6608495869,18.7994366884,47.6624248446`, the APIv2 returns detections, but these are all outside the bounding box. The detection inside the bounding box is not returned:

Click on "Details" below to see the response I get when requesting `https://a.mapillary.com/v2/search/im/or?minlon=18.7965613604&minlat=47.6608495869&maxlon=18.7994366884&maxlat=47.6624248446&client_id=‹my_client_id›`
<details>
<pre>
{
  "more": true,
  "ims": [
    {
      "ca": 42.00457000732422,
      "key": "YdzD-xohFq2nnnaSHwKbjg",
      "lat": 55.81949234008789,
      "lon": 37.43681335449219,
      "rects": [
        {
          "score": "0.313415972094",
          "package": "trafficsign_eu_1.0",
          "rect": [
            0.8095703125,
            0.40234375,
            0.8515625,
            0.4791666666666667
          ],
          "type": "other_give_way"
        }
      ],
      "country": "Russian Federation",
      "user": "trolleway"
    },
    {
      "ca": 271.79534912109375,
      "key": "JHWzJY6rwEJwvj7TSt2u2A",
      "lat": 55.81932067871094,
      "lon": 37.43632125854492,
      "rects": [
        {
          "score": "0.00431655390136",
          "package": "trafficsign_eu_1.0",
          "rect": [
            0.775390625,
            0.9140625,
            0.7939453125,
            0.9388020833333334
          ],
          "type": "danger_intersection"
        }
      ],
      "country": "Russian Federation",
      "user": "trolleway"
    },
    {
      "ca": 45.30147171020508,
      "key": "0wm0145rw0dwtBoLfCeNYw",
      "lat": 55.819793701171875,
      "lon": 37.437416076660156,
      "rects": [
        {
          "score": "0.417654200014",
          "package": "trafficsign_eu_1.0",
          "rect": [
            0.8603515625,
            0.3893229166666667,
            0.8974609375,
            0.4505208333333333
          ],
          "type": "other_give_way"
        }
      ],
      "rectversions": [
        {
          "timestamp": 1455015935269,
          "package": "trafficsign_eu_1.0",
          "user": "bfdYMOY97Z0w3ioPyItcUg",
          "rects": []
        }
      ],
      "country": "Russian Federation",
      "user": "trolleway"
    },
    {
      "ca": 144.08535766601562,
      "key": "snvbbHcjvTqcMp67dhAipA",
      "lat": 55.820457458496094,
      "lon": 37.43983840942383,
      "rects": [
        {
          "score": "1.152742008",
          "package": "trafficsign_eu_1.0",
          "rect": [
            0.146484375,
            0.5885416666666666,
            0.1669921875,
            0.6184895833333334
          ],
          "type": "other_no_entry"
        },
        {
          "score": "0.381656952163",
          "package": "trafficsign_eu_1.0",
          "rect": [
            0.427734375,
            0.4739583333333333,
            0.4482421875,
            0.4973958333333333
          ],
          "type": "other_priority_road"
        },
        {
          "score": "0.570034413361",
          "package": "trafficsign_eu_1.0",
          "rect": [
            0.396484375,
            0.5234375,
            0.421875,
            0.5520833333333334
          ],
          "type": "other_priority_road"
        }
      ],
      "country": "Russian Federation",
      "user": "trolleway"
    },
    {
      "ca": 5.128725051879883,
      "key": "KSyojvza4v24gp851VMZYg",
      "lat": 44.378607398830354,
      "lon": 26.091781295835972,
      "rects": [
        {
          "score": "0.079311143564",
          "package": "trafficsign_eu_1.0",
          "rect": [
            0.6689453125,
            0.4205729166666667,
            0.6982421875,
            0.4622395833333333
          ],
          "type": "prohibitory_no_parking"
        }
      ],
      "country": "Romania",
      "user": "streetview_romania"
    },
    {
      "ca": 17.736469268798828,
      "key": "3Ak5CjEuG_j2TxnZlpDFsQ",
      "lat": 55.81682205200195,
      "lon": 37.43438720703125,
      "rects": [
        {
          "score": "1.87438737611",
          "package": "trafficsign_eu_1.0",
          "rect": [
            0.1015625,
            0.45703125,
            0.125,
            0.4973958333333333
          ],
          "type": "other_no_entry"
        }
      ],
      "country": "Russian Federation",
      "user": "trolleway"
    },
    {
      "ca": 270.244873046875,
      "key": "s_toYPsR0N9arqj0EdgWcQ",
      "lat": 55.81932067871094,
      "lon": 37.43623352050781,
      "rects": [
        {
          "score": "0.346581195206",
          "package": "trafficsign_eu_1.0",
          "rect": [
            0.4970703125,
            0.3841145833333333,
            0.54296875,
            0.4635416666666667
          ],
          "type": "other_give_way"
        }
      ],
      "rectversions": [
        {
          "timestamp": 1443787911236,
          "package": "trafficsign_eu_1.0",
          "user": "OGaDFWpyTIYjypXkOVRbwg",
          "rects": []
        }
      ],
      "country": "Russian Federation",
      "user": "trolleway"
    },
    {
      "ca": -1,
      "key": "8BmcLbuy2O62qRRG-gJc6Q",
      "lat": 44.37969476010101,
      "lon": 26.097118559900682,
      "rects": [
        {
          "package": "trafficsign_eu_1.0",
          "score": "0.39716706421",
          "rect": [
            0.9384765625,
            0.22395833333333334,
            0.9765625,
            0.2799479166666667
          ],
          "type": "prohibitory_speed_limit_30"
        }
      ],
      "country": "Romania",
      "user": "streetview_romania"
    },
    {
      "ca": -1,
      "key": "Y8ujKP3WzXvWs94A-fuNcQ",
      "lat": 44.37969476010101,
      "lon": 26.097118559900682,
      "rects": [
        {
          "package": "trafficsign_eu_1.0",
          "score": "0.884370682344",
          "rect": [
            0.69140625,
            0.4557291666666667,
            0.7138671875,
            0.48828125
          ],
          "type": "other_no_entry"
        }
      ],
      "country": "Romania",
      "user": "streetview_romania"
    },
    {
      "ca": 89.99997939579018,
      "key": "f-uSD3O5ksLQYOB50fMLEw",
      "lat": 55.50065,
      "lon": 37.568690000000004,
      "rects": [
        {
          "score": "0.0325561418918",
          "package": "trafficsign_eu_1.0",
          "rect": [
            0.7099609375,
            0.14453125,
            0.7353515625,
            0.18359375
          ],
          "type": "danger_uneven_road"
        }
      ],
      "rectversions": [
        {
          "timestamp": 1429486135336,
          "package": "trafficsign_eu_1.0",
          "user": "bKgtniVKsrEvfpVk0r2b7A",
          "rects": []
        }
      ],
      "country": "Russian Federation",
      "user": "trolleway"
    }
  ]
}
</pre>
</details><br>

APIv3 returns the correct result for `https://a.mapillary.com/v3/detections?bbox=18.7965613604,47.6608495869,18.7994366884,47.6624248446&client_id=‹my_client_id›`
<details>
<pre>
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "area": 0.00031288046264257396,
        "image_key": "-3kBQL589ZOAr48Es4n-Xg",
        "key": "5hf3rpnidpr53m651sn1o1f742",
        "package": "trafficsign",
        "score": 0.997906,
        "shape": {
          "type": "Polygon",
          "coordinates": [
            [
              [
                0.41845703125,
                0.443603515625
              ],
              [
                0.433837890625,
                0.443603515625
              ],
              [
                0.433837890625,
                0.4638671875
              ],
              [
                0.41845703125,
                0.4638671875
              ],
              [
                0.41845703125,
                0.443603515625
              ]
            ]
          ]
        },
        "value": "warning--uneven-road--g1"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          18.798834000000003,
          47.661352
        ]
      }
    }
  ]
}
</pre>
</details><br>

So this is clearly a bug in the API, but because this is already fixed in version 3, it probably won't be fixed in version 2.
When the next release of the plugin is released, this won't be a problem anymore, because as I wrote, the next release will use APIv3.

cc @peterneubauer

**Comment by floscher** [comment] 2017-04-10 15:45
This is now resolved, I just released version 1.5.0 of the plugin. :tada:
You can now even see, which signs are detected (as overlay on the image, or as separate "Map object layer"):
![grafik](https://cloud.githubusercontent.com/assets/3904348/24870038/583bf1a4-1e15-11e7-8086-e33972044fa7.png)

Simply update the plugin in the JOSM preferences and you are ready to test it.

**Comment by peterneubauer** [comment] 2017-04-10 18:18
Awesome progress, looks really nice!

**Comment by PolyglotOpenstreetmap** [comment] 2017-04-10 19:42
Indeed. It made me wonder though, is there a way to turn those overlays on and off? So we can verify the detections? And then the next question, but that's probably for another ticket. Is there a way to add signs from within JOSM? Or to indicate a recognition was wrong? And then the other thought that came to mind is, are these recognitions stored as objects on Mapillary's side. Say I map a sign on an OpenStreetMap node, can I add a pointer back Mapillary to indicate which sign I'm mapping?

**Comment by floscher** [comment] 2017-04-10 19:51
@PolyglotOpenstreetmap You can use the checkbox, which you see in the bottom right of the screenshot to toggle the overlay.

At the moment it's not possible to add or remove signs or give feedback on detections. I'm not even sure, if the APIv3 would allow this in the current state.

Yes, they are objects on the server side. Each map object has its own key, similar to the image key. So you could invent a tagging schema like `mapillary:object=qfd9ado7cgzavvzdaa6yoi1x87`. But at the moment most signs have multiple map objects in Mapillary. 

I'll close this issue again, because the issue which was reported here is solved. For other feature requests, we can open new issues.

**Closed by floscher** 2017-04-10 19:51 UTC
Labels: bug, not our fault

**Comment by peterneubauer** [comment] 2017-04-11 08:43
Also, traffic signs are just a special case of detections filtered by class. Going forward, the same call will return actual classified polygons that can be edited and audited back. API coming soon.

**Comment by floscher** [comment] 2017-04-11 15:02
@peterneubauer 

The plugin actually would also handle arbitrary polygons as well, even if the traffic sign detections weren't all rectangles. That's why I called them `ImageDetection` and not `MapillarySign` :wink:.

**But** it would currently draw an icon for all detections across the bounding box of the polygon, so that needs improvement. Can you notify me, when the API will also return these other detections? It would be ideal, if you could also provide some example data (some typical example of what the API will return), so I could test the plugin against that.

The API documentation also mentions that detections can be of type `Geometry<Polygon|Point>`. Are there any detections, which are points, or can we safely ignore any `Point` geometries returned by the API (that's how it's currently done).

**Comment by peterneubauer** [comment] 2017-04-12 08:11
yes, the API we are using now should eventually deliver this, @ptpt is on this.

**Comment by ptpt** [comment] 2017-04-12 08:15
Thanks. It's tracked. I will ping here when we deliver it.

**Comment by grinapo** [comment] 2017-04-12 10:14
@peterneubauer actually having this functionality immediately revealed huge amounts of really funny misdetections (plenty of them in patterns of branches of trees). What's the preferred way to handle these en masse? (I'll check how simple is to get back to the image from the plugin, I guess these only fixable through the web gui as of now.)

**Comment by peterneubauer** [comment] 2017-04-12 10:58
The preferred way is to submit audits to the detections, @gyllen and me are
working on this right now and will expose it in the API very soon!
