### ISSUE TITLE
It is not possible to login

### ISSUE THREAD

**Issue by angoca** [JOSM/Mapillary#187] opened 2021-07-05 00:33 UTC
When I try to login from the JOSM plugin, I get
App not found
From the web page.

**Comment by floscher** [comment] 2021-07-05 06:29
Possible duplicate of #183, haven't tried if it really is already fixed.

**Comment by nevw** [comment] 2021-07-07 17:00
I also am unable to login to Mapillary in Josm. Opens web page but remains blank.

**Comment by tsmock** [comment] 2021-07-14 16:53
@angoca : What version of the plugin are you using?
@nevw : It shows `null` since I don't currently have a way to get the current user information. IIRC, the `Login`/`Logout` button checks that the user name is not `null`, so I have to fix that, either by getting an API for current user information (unlikely right now, unfortunately), or just by checking that the OAuth token exists in preferences.

**Comment by tsmock** [comment] 2021-07-14 17:07
I'm closing this as a duplicate of #183. At least, comment 1 is a duplicate. Comment 3 is not, but I do know it is an issue.

**Closed by tsmock** 2021-07-14 17:07 UTC
