### ISSUE TITLE
Incorrect display of points and lines

### ISSUE THREAD

**Issue by tkoval83** [JOSM/Mapillary#133] opened 2020-09-16 08:25 UTC
Hi,
I have weird behaviour of plugin in JOSM 17013 using Java 11, see attached image.
But when I use Java 8 all workd fine.
<img width="2628" alt="Знімок екрана 2020-09-16 о 11 19 06" src="https://user-images.githubusercontent.com/14796309/93311946-4b50b600-f80f-11ea-99ae-f01fcba5e6b7.png">

**Comment by johsin18** [comment] 2020-09-18 07:08
Your problem is caused by having the screen scaling set to about 200%, probably you have a hidpi (Retina) screen. I have the same problem.  Java 8 is not affected, as it does not support hidpi (leading to ugly icons and many other problems in JOSM).
Mapillary team, could you fix this please.  IIRC this used to work in former times.

**Comment by tkoval83** [comment] 2020-09-18 12:26
@johsin18 Yes, I am using MacBook with 16 inch retina display.

**Comment by GhostFoxSledgehammer** [comment] 2020-09-24 06:29
This was fixed in this [commit](https://github.com/JOSM/Mapillary/commit/f061b0111e02f3ca7af0fd934cb8268675ac6c61) but was overwritten in this [one](https://github.com/JOSM/Mapillary/commit/259e039cf89b74dac0e142113076469dbb0bdb85), so the fix was never released. I'm not sure when but this should be fixed in the next release.

**Comment by tsmock** [comment] 2020-10-14 21:20
This has been fixed (I merged in @GhostFoxSledgehammer's fix).

**Closed by tsmock** 2020-10-14 21:20 UTC
