### ISSUE TITLE
Mapillary plugin failing

### ISSUE THREAD

**Issue by abhisheksaikia** [JOSM/Mapillary#13] opened 2016-07-27 13:35 UTC
The mapillary plugin is constantly failing with the following bug report:

<details>

```
{{{
URL:http://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2016-07-11 23:04:49 +0200 (Mon, 11 Jul 2016)
Build-Date:2016-07-12 01:31:48
Revision:10526
Relative:URL: ^/trunk

Identification: JOSM/1.5 (10526 en) Mac OS X 10.11.6
Memory Usage: 444 MB / 910 MB (292 MB allocated, but free)
Java version: 1.8.0_101-b13, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
VM arguments: [-Djava.security.policy=file:<java.home>/lib/security/javaws.policy, -DtrustProxy=true, -Djnlpx.home=<java.home>/bin, -Djava.security.manager, -Djnlpx.origFilenameArg=${HOME}/Library/Application Support/Oracle/Java/Deployment/cache/6.0/56/1ee8cfb8-56c770eb, -Djnlpx.remove=false, -Dsun.awt.warmup=true, -Djava.util.Arrays.useLegacyMergeSort=true, -Dmacosx.jnlpx.dock.name=JOSM, -Dmacosx.jnlpx.dock.icon=${HOME}/Library/Application Support/Oracle/Java/Deployment/cache/6.0/16/47ee53d0-41edb0af.icns, -Djnlp.application.href=https://josm.openstreetmap.de/download/josm.jnlp , -Djnlpx.jvm="<java.home>/bin/java", -Djnlpx.vmargs=LURqYXZhLnV0aWwuQXJyYXlzLnVzZUxlZ2FjeU1lcmdlU29ydD10cnVlAC1Eam5scC5hcHBsaWNhdGlvbi5ocmVmPWh0dHBzOi8vam9zbS5vcGVuc3RyZWV0bWFwLmRlL2Rvd25sb2FkL2pvc20uam5scCAA]
Dataset consistency test: No problems found

Plugins:
- FastDraw (32639)
- Mapillary (32639)
- RoadSigns (32584)
- apache-commons (32584)
- apache-http (32584)
- auto_tools (1468620578)
- buildings_tools (32639)
- colorscheme (32584)
- continuosDownload (53)
- ejml (32639)
- fieldpapers (v0.4.0)
- geotools (32584)
- josm-config (1449603193)
- jts (32539)
- opendata (32584)
- reltoolbox (32639)
- reverter (32584)
- scripting (30723)
- terracer (32426)
- todo (29154)
- turnlanes (32584)
- turnlanes-tagging (1468266519)
- turnrestrictions (32629)
- utilsplugin2 (32584)

Tagging presets:
- https://josm.openstreetmap.de/josmfile?page=Presets/LaneAttributes&zip=1
- https://josm.openstreetmap.de/josmfile?page=Presets/Quick-highways&zip=1

Map paint styles:
- https://josm.openstreetmap.de/josmfile?page=Styles/Coloured_buildings&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Lane_and_Road_Attributes&zip=1
- https://raw.githubusercontent.com/Andygol/josm-styles/master/created_in_2015.mapcss

Last errors/warnings:
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- E: javax.json.JsonException: I/O error while parsing JSON. Cause: javax.net.ssl.SSLException: SSL peer shut down incorrectly
- E: javax.json.JsonException: I/O error while parsing JSON. Cause: javax.net.ssl.SSLException: SSL peer shut down incorrectly

javax.json.JsonException: I/O error while parsing JSON
    at org.glassfish.json.JsonTokenizer.read(JsonTokenizer.java:444)
    at org.glassfish.json.JsonTokenizer.readNumberChar(JsonTokenizer.java:243)
    at org.glassfish.json.JsonTokenizer.readNumber(JsonTokenizer.java:272)
    at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:410)
    at org.glassfish.json.JsonParserImpl$ArrayContext.getNextEvent(JsonParserImpl.java:303)
    at org.glassfish.json.JsonParserImpl$StateIterator.next(JsonParserImpl.java:172)
    at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:149)
    at org.glassfish.json.JsonReaderImpl.readArray(JsonReaderImpl.java:136)
    at org.glassfish.json.JsonReaderImpl.readArray(JsonReaderImpl.java:139)
    at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:180)
    at org.glassfish.json.JsonReaderImpl.readArray(JsonReaderImpl.java:143)
    at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:180)
    at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:103)
    at org.openstreetmap.josm.plugins.mapillary.io.download.MapillarySequenceDownloadThread.run(MapillarySequenceDownloadThread.java:59)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLException: SSL peer shut down incorrectly
    at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:596)
    at sun.security.ssl.InputRecord.read(InputRecord.java:532)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
    at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
    at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
    at sun.net.www.http.ChunkedInputStream.fastRead(ChunkedInputStream.java:244)
    at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:689)
    at java.io.FilterInputStream.read(FilterInputStream.java:133)
    at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3336)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.BufferedReader.fill(BufferedReader.java:161)
    at java.io.BufferedReader.read1(BufferedReader.java:212)
    at java.io.BufferedReader.read(BufferedReader.java:286)
    at org.glassfish.json.JsonTokenizer.fillBuf(JsonTokenizer.java:473)
    at org.glassfish.json.JsonTokenizer.read(JsonTokenizer.java:434)
    ... 16 more
}}} 
```

<details>

**Comment by floscher** [comment] 2016-07-27 14:06
Thank you for reporting this. Are you experiencing this only recently, or for some time now?

I'll have a look at it and at least avoid the full crash and just inform the user that the download failed.
But at least from the first look it seems that I can't do more about the issue, because it looks like the server shut down the SSL-connection unexpectedly.

cc @peterneubauer: Could it be that the API currently has issues with SSL-connections? I haven't tested yet, just a thought given the stacktrace.

**Comment by abhisheksaikia** [comment] 2016-07-28 04:55
@floscher This is more recent thing. I have extensively used mapillary plugin previously and it was 👍

**Comment by geohacker** [comment] 2016-07-28 07:07
cc @gyllen

**Comment by peterneubauer** [comment] 2016-07-28 21:16
For me this is working now, was probably a temporary API failure. Closing for now.

**Comment by floscher** [comment] 2016-07-28 21:39
I also wasn't able to reproduce the problem myself.

Also, @abhisheksaikia have you tried, if it works when you try another internet connection?

Nevertheless, I'll keep the issue open, because such an exception should not crash the whole plugin.

**Comment by peterneubauer** [comment] 2016-08-09 13:05
https://github.com/floscher/josm-mapillary-plugin/pull/17 should fix this.

**Comment by floscher** [comment] 2016-08-09 13:12
@peterneubauer I'm not sure, if it really does, because this issue occured when [downloading sequences](https://github.com/floscher/josm-mapillary-plugin/blob/85debbcc620a3c78f4deb7d319e0f649c42d57ff/src/org/openstreetmap/josm/plugins/mapillary/utils/MapillaryURL.java#L117), but #17 fixes the [OAuth-URL](https://github.com/floscher/josm-mapillary-plugin/blob/85debbcc620a3c78f4deb7d319e0f649c42d57ff/src/org/openstreetmap/josm/plugins/mapillary/utils/MapillaryURL.java#L67).

Or am I missing something?

**Comment by floscher** [comment] 2016-09-21 19:09
I was now able to reproduce the problem at least once using version 81643fcce748b3f2df45d09b3276768a45dbfe91:

<details>
URL:http://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2016-09-06 00:16:07 +0200 (Tue, 06 Sep 2016)
Build-Date:2016-09-05 22:21:00
Revision:10966
Relative:URL: ^/trunk

Identification: JOSM/1.5 (10966 de) Linux Ubuntu 16.04.1 LTS
Memory Usage: 555 MB / 3545 MB (264 MB allocated, but free)
Java version: 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14, Oracle Corporation, OpenJDK 64-Bit Server VM
Screen: :0.0 3200x1800
Maximum Screen Size: 3200x1800
Java package: openjdk-8-jre:amd64-8u91-b14-3ubuntu1~16.04.1
Java ATK Wrapper package: libatk-wrapper-java:all-0.33.3-6
VM arguments: [-Djosm.home=<josm.pref>, -Dfile.encoding=UTF-8, -Duser.country=DE, -Duser.language=de, -Duser.variant]
Dataset consistency test: No problems found

Plugins:
+ Mapillary (31976)
+ apache-commons (32699)
+ apache-http (32699)

Last errors/warnings:
- W: Old style SideButton usage for action org.openstreetmap.josm.plugins.mapillary.gui.MapillaryChangesetDialog$SubmitAction@65d53819
- W: Unable to get color from '' for color preference 'extrude.main.line'
- W: Unable to get color from '' for color preference 'improve.way.accuracy.helper.line'
- W: Unable to get color from '' for color preference 'make.parallel.helper.line'


=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: pool-3-thread-1 (61)
javax.json.JsonException: I/O error while parsing JSON
	at org.glassfish.json.JsonTokenizer.read(JsonTokenizer.java:444)
	at org.glassfish.json.JsonTokenizer.readNumberChar(JsonTokenizer.java:243)
	at org.glassfish.json.JsonTokenizer.readNumber(JsonTokenizer.java:272)
	at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:410)
	at org.glassfish.json.JsonParserImpl$ArrayContext.getNextEvent(JsonParserImpl.java:314)
	at org.glassfish.json.JsonParserImpl$StateIterator.next(JsonParserImpl.java:172)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:149)
	at org.glassfish.json.JsonReaderImpl.readArray(JsonReaderImpl.java:136)
	at org.glassfish.json.JsonReaderImpl.readArray(JsonReaderImpl.java:139)
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:180)
	at org.glassfish.json.JsonReaderImpl.readArray(JsonReaderImpl.java:143)
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:180)
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:103)
	at org.openstreetmap.josm.plugins.mapillary.io.download.MapillarySequenceDownloadThread.run(MapillarySequenceDownloadThread.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:596)
	at sun.security.ssl.InputRecord.read(InputRecord.java:532)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.ChunkedInputStream.fastRead(ChunkedInputStream.java:244)
	at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:689)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3336)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.read1(BufferedReader.java:212)
	at java.io.BufferedReader.read(BufferedReader.java:286)
	at org.glassfish.json.JsonTokenizer.fillBuf(JsonTokenizer.java:473)
	at org.glassfish.json.JsonTokenizer.read(JsonTokenizer.java:434)
	... 16 more
</details>

**Comment by floscher** [comment] 2016-09-21 20:24
Duplicates of this ticket:
https://josm.openstreetmap.de/ticket/13338
https://josm.openstreetmap.de/ticket/13490
https://josm.openstreetmap.de/ticket/13498

**Comment by floscher** [comment] 2017-04-20 13:34
Since f71dd9b5cd830b7cdb56cad0c58b26171267990e all of these JsonExceptions should be catched and a Notification appears to inform the user that the download failed.
This will avoid such crashes. The problem is probably most of the time a weak internet connection or an API failure, which causes the connection to be terminated or the JSON to be malformed.

The change will roll out with the next release after `v1.5.3`, which will be published soon.

**Closed by floscher** 2017-04-20 13:34 UTC
Labels: bug
