### ISSUE TITLE
double click bug

### ISSUE THREAD

**Issue by Stefal** [JOSM/Mapillary#115] opened 2020-04-08 06:19 UTC
Hi,
With the latest release 1.5.21, Josm 16239, 1.8.0_191-b12, Windows 10, if you have a selected image, and you double click anyhere on the active osm layer, it removes the image from the viewer.

**Comment by taylorsmock** [comment] 2020-04-08 13:38
This was actually by design, so that the current image and image sequence would be deselected. Do you have an alternative method to deselect the current image and image sequence?

If it makes sense, I'm open to doing it (may be awhile -- depends upon other time commitments), or taking pull requests.

**Comment by Stefal** [comment] 2020-04-08 14:20
Is it a useful feature to deselect an image/sequence ?

Double click is already a Josm mouse "shortcut" to select the enclosing area, so I don't think it's a good idea to reuse it for another feature on an unselected layer.

**Comment by taylorsmock** [comment] 2020-04-08 17:43
I did know that it was a JOSM mouse shortcut. I also know that OpenStreetCam requires more clicks, but it has always been semi-broken for me.

I'll make a build that requires three clicks, and you can get back to me if that works well for deselecting the sequence. I'll be able to test later myself.

I also added a preference key (`mapillary.image.deselect.click.count`) that you can change in advanced preferences if you don't like `3` as the click count. _This is an unreleased version_.

[Mapillary.jar.zip](https://github.com/JOSM/Mapillary/files/4451979/Mapillary.jar.zip)
You will have to remove the `.zip` and place it in the JOSM plugin directory.

**Comment by taylorsmock** [comment] 2020-04-27 14:25
I'm closing this, since you can now set the click count in advanced preferences, and it defaults to a triple-click.

**Closed by taylorsmock** 2020-04-27 14:25 UTC

**Comment by zzptichka** [comment] 2020-05-04 02:48
Does it work? Just tried this version setting `mapillary.image.deselect.click.count` to 2,3,4, the image always disappears after double click. Tried restarting.

**Comment by taylorsmock** [comment] 2020-05-04 14:14
Yes. I did make a mistake in the initial patch, but it is fixed now (in an unreleased branch).

Sorry about that.

(See https://gitlab.com/gokaart/josm-mapillary-plugin/-/commit/21642ec0d47d499027ddf9a943aad9c323b37b1c )
